### ISSUE TITLE
Error: Cannot find module 'node-red-dashboard'

### ISSUE THREAD

**Issue by pkjq** [hotNipi/node-red-contrib-ui-level#7]
**Describe the bug**
> node-red[1452]: { Error: Cannot find module 'node-red-dashboard'
> node-red[1452]:     at Object.requireModule [as require] (**/usr/local/lib/node_modules/node-red/node_modules/**@node-red/registry/lib/util.js:48:19)
> node-red[1452]:     at new LevelNode (/var/smarthouse/nodered/.node-red/node_modules/node-red-contrib-ui-level/ui-level.js:176:14)
> node-red[1452]:     at Object.createNode (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
> node-red[1452]:     at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:176:44)
> node-red[1452]:     at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
> node-red[1452]:     at stop.then.then (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
> node-red[1452]:     at processTicksAndRejections (internal/process/task_queues.js:86:5) code: 'MODULE_NOT_FOUND' }

**To Reproduce**
Clear setup node-red.
Then install node-red-dashboard and node-red-contrib-ui-level from node-red interface.
Run with option -u:
> ExecStart=/usr/local/bin/node-red -u **/var/smarthouse/nodered/.node-red**

**Desktop (please complete the following information):**
 - OS: raspberry debian
 - Node-RED version: 0.20.5
 - Dashboard version: 2.14.0
 - ui-level version: 0.0.15

**Comment by hotNipi** [comment]
Node can not know where it is installed and if it can be reached. 
It might be mistake on installation or wrong usage of --userDIR flag but being not so familiar with linux environments I can't give strong advise.
You should rise topic in https://discourse.nodered.org to get help on this issue.

Meanwhile I leave this issue open until I see it is sorted out

**Comment by hotNipi** [comment]
Closing as no activity and no issue at node level.

**Comment by Nodi-Rubrum** [comment]
Any way to not have ui-level colorize the minimum and maximum ticks in the bar?  Not understanding why they are colorized when the value is zero.
